//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Cid { get; set; }
        public string CatType { get; set; }
        public int ProductPid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
