//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Sid { get; set; }
        public string Sname { get; set; }
        public int MarksObtained { get; set; }
        public int ResultRid { get; set; }
    
        public virtual Result Result { get; set; }
    }
}
